name: LWC-iConomy
main: com.griefcraft.bukkit.LWCiConomyPlugin
version: 1.02
website: http://griefcraft.com
author: Hidendra
description: iConomy module for LWC to allow protections to be purchased using iConomy money.
depend:
    - LWC
    - iConomy