name: LWC-Economy
main: com.griefcraft.bukkit.LWCEconomyPlugin
version: 1.30
website: http://griefcraft.com
author: Hidendra
description: Economy module for LWC to allow protections to be purchased using currency.
load: POSTWORLD