worldguard:
    enabled: false

    # If the player needs to have build rights in a region to be able to protect blocks using LWC
    requireBuildRights: true

    # Regions that LWC protections SHOULD be allowed in
    regions:
        - '*'

    # Regions that LWC protections should NOT be allowed in
    blacklistedRegions:
        - 'Region1'