name: LWC
main: com.griefcraft.lwc.LWCPlugin
version: 2.00
website: http://griefcraft.com
author: Hidendra
description: >
             Inventory protection & management utilizing SQLite or MySQL as its backend
             Other blocks can be protected such as Doors and Signs
commands:
  lwc:
    description: LWC's hub command to access everything
    usage: /<command>
  cpublic:
    description: Alias command for /lwc -c public
    usage: /<command>
  cpassword:
    description: Alias command for /lwc -c password <password>
    usage: /<command> <password>
  cprivate:
    description: Alias command for /lwc -c private
    usage: /<command> <Users/Groups>
  cmodify:
    description: Alias command for /lwc -m
    usage: /<command> <Modifications>
  cunlock:
    description: Alias command for /lwc -u <password>
    usage: /<command> <password>
  cinfo:
    description: Alias command for /lwc -i
    usage: /<command>
  cremove:
    description: Alias command for /lwc -r protection
    usage: /<command>