name: LWC-iConomy
main: com.griefcraft.bukkit.BukkitPlugin
version: 1.00
website: http://griefcraft.com
author: Hidendra
description: LWC iConomy module to allow protections to be purchased using iConomy money.
depend:
    - LWC
    - iConomy